export type UiLocale = "en" | "ko";

export const UI_STRINGS = {
  en: {
    shellEyebrow: "Local Simulation Client",
    shellTitle: "End4D Workbench",
    nav: {
      overview: "Overview",
      simulation: "Simulation",
      reviewLab: "Review",
      dataPacks: "Data Management",
      snapshots: "Snapshots",
      policyLab: "Policy Lab",
    },
    runtime: "Runtime",
    packs: "Packs",
    regions: "Regions",
    language: "Language",
    runtimeDockTitle: "Runtime",
    runtimeDockSubtitle: "Local engine status",
    api: "API",
    llm: "LLM",
    llmAuth: "LLM Auth",
    llmProfile: "LLM Profile",
    strictMode: "Strict Mode",
    providerHealth: "Provider Health",
    manifest: "Manifest",
    cache: "Cache",
    noApiKey: "No API key",
    keySet: "key set",
    waitingRuntime: "Waiting for runtime",
    runtimeLoadError: "Failed to load runtime status",
    llmActivityTitle: "LLM Activity",
    llmActivitySubtitle: "Recent live cognition and fallback pressure",
    recentCalls: "Recent Calls",
    liveRate: "Live Rate",
    fallbackRate: "Fallback Rate",
    degradedTasks: "Degraded Tasks",
    dominantFailure: "Dominant Failure",
    recommendedActions: "Recommended Actions",
    taskInsights: "Task Insights",
    taskInsightsSubtitle: "Which cognition loops are truly live vs clipped",
    noLlmActivity: "No LLM activity yet.",
    installedPacksTitle: "Installed Packs",
    installedPacksSubtitle: "Cloud-fed persona packs cached locally",
    noInstalledPacks: "No installed data packs yet.",
    licensePending: "License info pending",
    configuredVia: "configured via",
    autoFit: "Auto Fit",
    balanced: "Balanced",
    focusViz: "Focus Viz",
    wideControls: "Wide Controls",
    openDataPacks: "Open Data Packs",
    openReviewLab: "Open Review Lab",
    runWithStream: "Run with stream",
    runSync: "Run sync",
    runtimeReadyLocal: "When the local runtime is ready, this machine computes directly.",
    simulationWorkspace: "Simulation Workspace",
    twoStepFlow: "Two-step setup and execution flow",
    setup: "Setup",
    run: "Run",
    backToSetup: "Back to Setup",
  },
  ko: {
    shellEyebrow: "로컬 시뮬레이션 클라이언트",
    shellTitle: "End4D 워크벤치",
    nav: {
      overview: "개요",
      simulation: "시뮬레이션",
      reviewLab: "리뷰",
      dataPacks: "데이터 관리",
      snapshots: "스냅샷",
      policyLab: "정책 실험실",
    },
    runtime: "런타임",
    packs: "팩",
    regions: "지역",
    language: "언어",
    runtimeDockTitle: "런타임",
    runtimeDockSubtitle: "로컬 엔진 상태",
    api: "API",
    llm: "LLM",
    llmAuth: "LLM 인증",
    llmProfile: "LLM 프로필",
    strictMode: "엄격 모드",
    providerHealth: "프로바이더 상태",
    manifest: "매니페스트",
    cache: "캐시",
    noApiKey: "API 키 없음",
    keySet: "키 설정됨",
    waitingRuntime: "런타임 대기 중",
    runtimeLoadError: "런타임 상태를 불러오지 못했습니다",
    llmActivityTitle: "LLM 활동",
    llmActivitySubtitle: "최근 실시간 cognition과 fallback 압력",
    recentCalls: "최근 호출",
    liveRate: "실시간 비율",
    fallbackRate: "폴백 비율",
    degradedTasks: "저하된 태스크",
    dominantFailure: "주요 실패 원인",
    recommendedActions: "권장 조치",
    taskInsights: "태스크 진단",
    taskInsightsSubtitle: "어떤 cognition 루프가 실제 live이고 어디가 잘리는지",
    noLlmActivity: "아직 LLM 호출 이력이 없습니다.",
    installedPacksTitle: "설치된 팩",
    installedPacksSubtitle: "클라우드에서 공급된 페르소나 팩의 로컬 캐시",
    noInstalledPacks: "아직 설치된 데이터 팩이 없습니다.",
    licensePending: "라이선스 정보 없음",
    configuredVia: "설정 경로",
    autoFit: "자동 맞춤",
    balanced: "균형",
    focusViz: "시각화 집중",
    wideControls: "컨트롤 확장",
    openDataPacks: "데이터 팩 열기",
    openReviewLab: "리뷰 랩 열기",
    runWithStream: "스트림 실행",
    runSync: "동기 실행",
    runtimeReadyLocal: "로컬 런타임이 준비되면 이 머신에서 바로 계산합니다.",
    simulationWorkspace: "시뮬레이션 워크스페이스",
    twoStepFlow: "설정과 실행을 분리한 2단계 흐름",
    setup: "설정",
    run: "실행",
    backToSetup: "설정으로",
  },
} as const;

export function getWorkbenchLabels(locale: UiLocale) {
  const nav = UI_STRINGS[locale].nav;
  return {
    overview: nav.overview,
    simulation: nav.simulation,
    "review-lab": nav.reviewLab,
    "data-packs": nav.dataPacks,
    snapshots: nav.snapshots,
    "policy-lab": nav.policyLab,
  } as const;
}
